pipeline {
    agent any
    environment {
        IMAGE_NAME = "demo"
    }

    stages {
        stage('Git Clone') {
            steps {
                // Checkout using SSH key-based authentication
            git changelog: false, credentialsId: 'jenkins', poll: false, url: 'git@github.com:kulkarni8888/Demo.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image from the repository
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }
    }
}
